object FormMain: TFormMain
  Left = 192
  Top = 150
  BorderStyle = bsNone
  Caption = 'MainForm'
  ClientHeight = 427
  ClientWidth = 862
  Color = clNavy
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  OnClose = FormClose
  OnCreate = FormCreate
  OnMouseDown = FormMouseDown
  PixelsPerInch = 96
  TextHeight = 13
end
